zalando-incubator/zalando-commerce-ios

AtlasSDK/AtlasSDKTests/APIClientSpec.swift
AtlasSDK/AtlasSDKTests/APICustomerSpec.swift
AtlasSDK/AtlasSDKTests/PublicAtlasSDKSpec.swift

Use testing id of client instead of generic one

Replace “clientId” with testing client

---

AtlasDemo/AtlasDemo.xcodeproj/project.pbxproj
AtlasMockAPI/AtlasMockAPI.xcodeproj/project.pbxproj
AtlasSDK/AtlasSDK.xcodeproj/project.pbxproj
AtlasUI/AtlasUI.xcodeproj/project.pbxproj
Gemfile
Gemfile.lock

Added Quick and Nimble to AtlasUITests

---

AtlasSDK/AtlasSDK.xcodeproj/project.pbxproj
AtlasSDK/AtlasSDK/APIRequestBuilder.swift
AtlasUI/AtlasUI.xcodeproj/project.pbxproj
AtlasUI/AtlasUI/Utils/Async.swift
AtlasUI/AtlasUITests/AsyncSpec.swift

Moved Async to AtlasUI

---

AtlasSDK/AtlasSDK.xcodeproj/project.pbxproj
AtlasSDK/AtlasSDK/Models/BillingAddress.swift
AtlasSDK/AtlasSDK/Models/Checkout.swift
AtlasSDK/AtlasSDK/Models/Order.swift
AtlasSDK/AtlasSDK/Models/Payment.swift
AtlasSDK/AtlasSDK/Models/PaymentMethod.swift
AtlasSDK/AtlasSDK/Models/ShippingAddress.swift
AtlasUI/AtlasUI/CheckoutService.swift
AtlasUI/AtlasUI/CheckoutSummaryViewController.swift

#47 - Connect Checkout API for shipping & billing addresses, also added terms & conditions

Issue 47 - Make shipping & billing addresses in Checkout UI

---

AtlasSDK/AtlasSDKTests/APICustomerSpec.swift

#14 - Fixed tests to point to mock server

---

AtlasDemo/AtlasDemo.xcodeproj/project.pbxproj
AtlasMockAPI/AtlasMockAPI.xcodeproj/project.pbxproj
AtlasSDK/AtlasSDK.xcodeproj/project.pbxproj
AtlasUI/AtlasUI.xcodeproj/project.pbxproj
buddybuild_postclone.sh

Might not be needed, as we don't run tests from script and notify anymore

#51: Removed buddybuild_postclone.sh

---

AtlasDemo/AtlasDemo/AppDelegate.swift
AtlasUI/AtlasUI/AtlasCheckout.swift

Small fix for transitioningDelegate (weak var)

Hotfix animations

---

AtlasMockAPI/AtlasMockAPI/JSON/POST*|checkouts.json

Removing internal link

---

AtlasSDK/AtlasSDK/APIRequestBuilder.swift
AtlasSDK/AtlasSDK/Utils/UIApplication.swift

- Added extra completion block in askUserToLogin
- Added extra completion block in execute when there’s no topViewController

#96: Added handling case when there’s no view controller to present login

---

AtlasUI/AtlasUI.xcodeproj/project.pbxproj
AtlasUI/AtlasUI/CheckoutSummaryRow.swift
AtlasUI/AtlasUI/CheckoutSummaryStyler.swift
AtlasUI/AtlasUI/CheckoutSummaryViewController.swift

Issue #94 Show incomplete form when user has missing data (Payment/Shipping)

Issue 94 - Show incomplete form when user has missing data

---

AtlasSDK/AtlasSDK.xcodeproj/project.pbxproj
AtlasUI/AtlasUI.xcodeproj/project.pbxproj
AtlasUI/AtlasUI/CheckoutSummaryRow.swift
AtlasUI/AtlasUI/CheckoutSummaryStyler.swift
AtlasUI/AtlasUI/CheckoutSummaryViewController.swift
AtlasUI/AtlasUI/PaymentSelectionViewController.swift

Issue #88 - Allow user to change payment method

Issue 88 - Allow user to change payment method

---

AtlasSDK/AtlasSDKTests/APIClientBaseSpec.swift
AtlasSDK/AtlasSDKTests/APICustomerSpec.swift
AtlasSDK/AtlasSDKTests/AtlasSpec.swift

Extended timeout in tests

---

.dummy-commit

Dummy commit to make travis build correctly.

Dummy commit

---

AtlasMockAPI/AtlasMockAPI/JSON/POST*|checkouts.json
AtlasUI/AtlasUI/CheckoutSummaryRow.swift
AtlasUI/AtlasUI/CheckoutSummaryStyler.swift

Issue #90  - Added enable/disable payment if no payment method selected

#90 - Added enable/disable payment if no payment method selected

---

.travis.yml
lib/calypso/run.rb
lib/calypso/xcode.rb

I know it's kind of hack, but it should help with UI and AtlasMockAPI hiccups.

Added number of test tries to run on travis

---

.codecov.yml

#136: Updated bot name to update git statuses

#136: Updated bot name to update git statuses

---

.travis.yml
AtlasDemo/AtlasDemoUITests/XCTestCase.swift

Not sure if it will help, but so far it seems so on travis...

#143: Removed UI tests from travis build

---

README.md

#80: Updated CocoaPods badges

---

AtlasUI/AtlasUI/PaymentProcessingViewController.swift
AtlasUI/AtlasUI/PaymentSelectionViewController.swift

Added payment confirmation screen (tested on Paypal)

Issue 156 - Added payment confirmation screen

---

AtlasUI/AtlasUI/CheckoutSummaryActionsHandler.swift
AtlasUI/AtlasUI/CheckoutSummaryStoryboard.storyboard
AtlasUI/AtlasUI/CheckoutSummaryStoryboardViewController.swift
AtlasUI/AtlasUI/PaymentSelectionViewController.swift

Issue #170  Fixed new UI with payment confirmation

Issue - 170 Fixed new UI with payment confirmation

---

CONTRIBUTING.md

#125: Small description about ZenHub added to CONTRIBUTING.

#125: Small description about ZenHub

---

AtlasSDK/AtlasSDK/APIRequestBuilder.swift
CONTRIBUTING.md

#189: unnecessary call to navigation controller removed

Issue 189: askUserToLogin: no Login WebView in case of navigation controller absence

---

CONTRIBUTING.md

- Calypso
- Removed Carthage requirement
- Remark about using external libraries

#145: Small updates in CONTRIBUTING.md

---

AtlasDemo/AtlasDemoUITests/AtlasDemoUITests.swift
AtlasUI/AtlasUI/CheckoutSummaryActionsHandler.swift
AtlasUI/AtlasUI/CheckoutSummaryViewController.swift

Hotfix for CheckoutAction in ActionsHandler

Hotfix for CheckoutAction in ActionsHandler

---

AtlasUI/AtlasUI/CheckoutSummaryPriceStackView.swift
AtlasUI/AtlasUI/de.lproj/Localizable.strings
AtlasUI/AtlasUI/en.lproj/Localizable.strings

#42: Added Vat included label

---

AtlasSDK/AtlasSDK/Models/Address.swift
AtlasSDK/AtlasSDK/Models/Addressable.swift
AtlasSDK/AtlasSDK/Models/Article.swift
AtlasSDK/AtlasSDK/Models/BillingAddress.swift
AtlasSDK/AtlasSDK/Models/ShippingAddress.swift
AtlasSDK/AtlasSDK/PublicAPIClient.swift
AtlasUI/AtlasUI/AddressListTableViewDelegate.swift
AtlasUI/AtlasUI/AtlasCheckout.swift
AtlasUI/AtlasUI/CheckoutSummaryActionsHandler.swift
AtlasUI/AtlasUI/CheckoutViewModel.swift
AtlasUI/AtlasUI/SizeListSelectionViewController.swift
AtlasUI/AtlasUI/SizeSelectionViewController.swift

#223: Added create checkout with previously selected addresses

#223: Added create checkout with previously selected addresses

---

AtlasSDK/AtlasSDK/Models/PaymentMethod.swift
AtlasUI/AtlasUI/CheckoutSummaryFooterStackView.swift
AtlasUI/AtlasUI/CheckoutSummaryViewController.swift
AtlasUI/AtlasUI/CheckoutViewModel.swift
AtlasUI/AtlasUI/CheckoutViewState.swift
AtlasUI/AtlasUI/de.lproj/Localizable.strings
AtlasUI/AtlasUI/en.lproj/Localizable.strings

#221: The place order button text changed for PayPal to "Confirm and pay with PayPal"

#221: The place order button text changed for PayPal 

---

AtlasUI/AtlasUI/CheckoutSummaryActionRowStackView.swift
calypso.rb

#215: after the short discussion with @ahmed-shehata we agree that address should be truncated and consists of 2 lines.

#215: address is truncated and consists of 2 lines now.

---

AtlasUI/AtlasUI/AddressRowViewCell.swift

#237: Fixed full name

---

AtlasSDK/AtlasSDK/Models/Delivery.swift
AtlasUI/AtlasUI/CheckoutSummaryPriceStackView.swift
AtlasUI/AtlasUI/de.lproj/Localizable.strings
AtlasUI/AtlasUI/en.lproj/Localizable.strings

- Fixed erliest key in Delivery
- Simplified delivery date formatting

Fix + refactor for delivery date

---

AtlasDemo/AtlasDemo.xcodeproj/project.pbxproj
AtlasDemo/AtlasDemo/AppDelegate.swift
AtlasDemo/AtlasDemo/AppSetup.swift
AtlasDemo/AtlasDemo/CatalogViewController.swift
AtlasDemo/AtlasDemo/Main.storyboard
AtlasDemo/AtlasDemo/ProductCollectionViewCell.swift
AtlasDemo/AtlasDemo/ProfileViewController.swift

Issue 243 - Introduce AppSetup for Switching Environments

---

AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|AD541L009-G11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|AZ711M001-B11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|AZ711N007-Q11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|AZ711N00B-Q11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|EV451G023-Q11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|GU121D08Z-Q11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|L2711E002-Q11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|LA254E005-Q11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|MK151F00E-Q11.json
AtlasSDK/AtlasSDK/Models/Article.swift
AtlasUI/AtlasUI/CheckoutSummaryProductStackView.swift

#275: Added color option to checkout summary

#275: Added color option to checkout summary

---

AtlasDemo/AtlasDemoUITests/AtlasDemoUITests.swift
AtlasUI/AtlasUI/AddressListTableViewDelegate.swift
AtlasUI/AtlasUI/AddressPickerViewController.swift
AtlasUI/AtlasUI/CheckoutSummaryActionsHandler.swift

Issue #282  - Enabled pop back to summary after selecting address

Issue 282 - Enabled pop back to summary after selecting address

---

AtlasUI/AtlasUI/AddressListTableViewDelegate.swift
AtlasUI/AtlasUI/AddressPickerViewController.swift

#278: Hide "Edit" button when all addresses are deleted

---

AtlasUI/AtlasUI.xcodeproj/project.pbxproj
AtlasUI/AtlasUI/AddressFormStackView.swift
AtlasUI/AtlasUI/AddressFormType.swift
AtlasUI/AtlasUI/AddressFormViewController.swift
AtlasUI/AtlasUI/AddressFormViewModel.swift
AtlasUI/AtlasUI/AddressPickerViewController.swift
AtlasUI/AtlasUI/de.lproj/Localizable.strings
AtlasUI/AtlasUI/en.lproj/Localizable.strings
AtlasUI/AtlasUITests/EditAddressTypeSpec.swift

Renaming`EditAddress` to `AddressForm`
Decided to do a separate PR before working on #281

Renaming  Address

---

AtlasDemo/AtlasDemoUITests/AtlasDemoUITests.swift
AtlasSDK/AtlasSDKTests/APIArticleSpec.swift
AtlasSDK/AtlasSDKTests/APIClientErrorsSpec.swift
AtlasUI/AtlasUI/AddressFormType.swift
AtlasUI/AtlasUI/AddressFormViewController.swift
AtlasUI/AtlasUI/AddressFormViewModel.swift
AtlasUI/AtlasUI/AddressPickerViewController.swift
AtlasUI/AtlasUITests/EditAddressTypeSpec.swift

#281: Go to summary view after creating new address

---

AtlasUI/AtlasUI/CheckoutSummaryActionsHandler.swift
AtlasUI/AtlasUI/CheckoutSummaryMainStackView.swift
AtlasUI/AtlasUI/CheckoutSummaryViewController.swift

working on #302 
The shipping and billing address were flipped when updating the checkout request

#302: Fix the addresses

---

.travis.yml
AtlasDemo/AtlasDemo/AppSetup.swift
AtlasSDK/AtlasSDK.xcodeproj/project.pbxproj
AtlasSDK/AtlasSDK/Endpoints/ConfigurableEndpoint.swift
AtlasSDK/AtlasSDK/Errors.swift
AtlasSDK/AtlasSDK/Models/Config.swift
AtlasSDK/AtlasSDK/Options.swift
AtlasSDK/AtlasSDK/OptionsInfoPlist.swift
AtlasSDK/AtlasSDK/RequestBuilder.swift
AtlasSDK/AtlasSDK/ResponseParser.swift
AtlasSDK/AtlasSDKTests/APIClientBaseSpec.swift
AtlasSDK/AtlasSDKTests/APIClientErrorsSpec.swift
AtlasSDK/AtlasSDKTests/AtlasSpec.swift
AtlasSDK/AtlasSDKTests/ConfigSpec.swift
AtlasSDK/AtlasSDKTests/Info.plist
AtlasSDK/AtlasSDKTests/OptionsSpec.swift
AtlasUI/AtlasUI/AtlasCheckout.swift
AtlasUI/AtlasUI/AtlasUIErrors.swift
lib/calypso/xcode.rb

#260: Dropped country from Options, allow to choose any language

#260: Dropped country from Options, allow to choose any language

---

AtlasDemo/AtlasDemo.xcodeproj/xcshareddata/xcschemes/AtlasDemo - Live API.xcscheme
AtlasDemo/AtlasDemo/AppSetup.swift
AtlasSDK/AtlasSDK/APIClient.swift
AtlasSDK/AtlasSDK/ConfigClient.swift
AtlasSDK/AtlasSDK/RequestBuilder.swift
AtlasSDK/AtlasSDK/ResponseParser.swift
AtlasUI/AtlasUI/AddressListTableViewDelegate.swift
AtlasUI/AtlasUI/AddressPickerViewController.swift

#307: Improve request logging

---

AtlasUI/AtlasUI.xcodeproj/project.pbxproj
AtlasUI/AtlasUI/AddressFormType.swift
AtlasUI/AtlasUI/Utils/FormValidator.swift

#309: returning the forms patterns

---

AtlasSDK/AtlasSDK/Endpoints/Endpoint.swift
AtlasSDK/AtlasSDK/Endpoints/GetArticlesEndpoint.swift
AtlasSDK/AtlasSDK/Endpoints/GetConfigEndpoint.swift
AtlasSDK/AtlasSDK/RequestBuilder.swift

#255: authorization token removed in GetArticle and Config request cause it is not needed by API

Issue 255: bad authorisation token

---

AtlasSDK/AtlasSDK/Info.plist
AtlasUI/AtlasUI/Info.plist
lib/version.rb

Not sure if I did it correctly, but just run manually commands from `pod.rb` (because `pod lib lint` doesn't work on my machine now.

Release 0.0.4

---

AtlasDemo/AtlasDemo.xcodeproj/project.pbxproj
AtlasDemo/AtlasDemo/AppDelegate.swift
AtlasDemo/AtlasDemo/AppDelegateBugBashingExtension.swift
AtlasSDK/AtlasSDK.xcodeproj/project.pbxproj
AtlasUI/AtlasUI.xcodeproj/project.pbxproj

#337: screenshot functionality added for bug bashing

#337: screenshot functionality added for bug bashing

---

AtlasUI/AtlasUI/CheckoutViewModel.swift
AtlasUI/AtlasUI/SizeSelectionViewController.swift

#345: The customer is nil in case of skipping the size selection

---

AtlasDemo/AtlasDemoUITests/AtlasDemoUITests.swift
AtlasMockAPI/AtlasMockAPI/JSON/GET*|config.json
AtlasSDK/AtlasSDK/Models/Config.swift
AtlasSDK/AtlasSDKTests/APIClientBaseSpec.swift
AtlasSDK/AtlasSDKTests/ConfigSpec.swift
AtlasUI/AtlasUI.xcodeproj/project.pbxproj
AtlasUI/AtlasUI/CheckoutSummaryFooterStackView.swift
AtlasUI/AtlasUI/ToCViewController.swift

#317: ToC lins dependant of sales channel added

#317: Add ToC link

---

AtlasUI/AtlasUI/SizeSelectionViewController.swift

#342: Removed "pick a size" if not yet fetched sizes

---

AtlasUI/AtlasUI/CheckoutSummaryFooterStackView.swift

#317 
**changing this** 
**to this**

#317: Enhancing the TOC button

---

AtlasDemo/AtlasDemo.xcodeproj/project.pbxproj
AtlasDemo/AtlasDemo/AppDelegateBugBashingExtension.swift
AtlasDemo/AtlasDemo/UIDeviceExtension.swift
AtlasDemo/AtlasDemoUITests/AtlasDemoUITests.swift
AtlasMockAPI/AtlasMockAPI/JSON/GET*|config.json
AtlasSDK/AtlasSDK/Models/Config.swift
AtlasSDK/AtlasSDKTests/APIClientBaseSpec.swift
AtlasSDK/AtlasSDKTests/ConfigSpec.swift
AtlasUI/AtlasUI.xcodeproj/project.pbxproj
AtlasUI/AtlasUI/CheckoutSummaryFooterStackView.swift
AtlasUI/AtlasUI/ToCViewController.swift

Issue 347: device info added

---

AtlasDemo/AtlasDemoUITests/AtlasDemoUITests.swift
AtlasMockAPI/AtlasMockAPI/JSON/GET*|config.json
AtlasSDK/AtlasSDK/Models/Config.swift
AtlasSDK/AtlasSDKTests/APIClientBaseSpec.swift
AtlasSDK/AtlasSDKTests/ConfigSpec.swift
AtlasUI/AtlasUI.xcodeproj/project.pbxproj
AtlasUI/AtlasUI/CheckoutSummaryActionsHandler.swift
AtlasUI/AtlasUI/CheckoutSummaryFooterStackView.swift
AtlasUI/AtlasUI/CheckoutSummaryViewController.swift
AtlasUI/AtlasUI/SizeSelectionViewController.swift
AtlasUI/AtlasUI/ToCViewController.swift

#348: Added fake order completion + disabled real order creation

#348: Added fake order completion + disabled real order creation

---

AtlasDemo/AtlasDemo.xcodeproj/xcshareddata/xcschemes/AtlasDemo - Live API.xcscheme
AtlasSDK/AtlasSDK/APIClient_public.swift
AtlasSDK/AtlasSDK/Models/Article.swift
AtlasSDK/AtlasSDK/RequestBuilder.swift
AtlasSDK/AtlasSDK/Utils/String.swift
AtlasSDK/AtlasSDKTests/APIArticleSpec.swift
AtlasUI/AtlasUI/CheckoutViewModel.swift
AtlasUI/AtlasUI/SizeListSelectionViewController.swift

working on #341 
+
enhancing API logs

#341: display size list even if only one size available

---

AtlasDemo/AtlasDemo.xcodeproj/xcshareddata/xcschemes/AtlasDemo.xcscheme
AtlasDemo/AtlasDemo/AppSetup.swift

#343: Added live production settings

---

AtlasUI/AtlasUI/AddressFormType.swift
AtlasUI/AtlasUI/Utils/FormValidator.swift
AtlasUI/AtlasUI/de.lproj/Localizable.strings
AtlasUI/AtlasUI/en.lproj/Localizable.strings
AtlasUI/AtlasUITests/FormValidatorSpec.swift

#330 
Not sure about the messages 😖

#330: Adding meaningful messages for regex pattern errors

---

AtlasDemo/AtlasDemo/AppSetup.swift
AtlasDemo/AtlasDemo/Main.storyboard
AtlasDemo/AtlasDemo/ProfileViewController.swift

#344: language switcher added

---

AtlasDemo/AtlasDemo.xcodeproj/xcshareddata/xcschemes/AtlasDemo.xcscheme
AtlasSDK/AtlasSDK/RequestBuilder.swift
AtlasUI/AtlasUI/CheckoutSummaryActionsHandler.swift

#324: Fixed bug where addresses would be both resetted

#324: Fixed bug where addresses would be both resetted

---

AtlasSDK/AtlasSDK/APIClient_public.swift
AtlasSDK/AtlasSDK/Models/Article.swift

#325: fixing bug where the sizes table could appear empty

---

AtlasDemo/AtlasDemo/AppDelegateBugBashingExtension.swift
AtlasUI/AtlasUI/AtlasUIViewController.swift

#373: presenting the email over the checkout 

---

AtlasDemo/AtlasDemo/AppSetup.swift
AtlasDemo/AtlasDemo/CatalogViewController.swift
AtlasDemo/AtlasDemo/ProfileViewController.swift

Fixes #380: loosing other settings when changing language / sandbox

#380: Fixes #380: loosing other settings when changing language / sandbox

---

AtlasDemo/AtlasDemo/AppSetup.swift
AtlasDemo/AtlasDemo/Main.storyboard
AtlasDemo/AtlasDemo/ProfileViewController.swift

#384: Added segmented control switch for server

#384: Added segmented control switch for server

---

AtlasUI/AtlasUI.xcodeproj/project.pbxproj
AtlasUI/AtlasUI/BannerErrorViewController.swift
AtlasUI/AtlasUI/CheckoutSummaryActionsHandler.swift
AtlasUI/AtlasUI/Utils/AtlasResult.swift
AtlasUI/AtlasUI/Utils/AtlasUI-String.swift
AtlasUI/AtlasUI/Utils/UIView.swift

#327: banner error

---

AtlasUI/AtlasUI/AtlasUIErrors.swift
AtlasUI/AtlasUI/Utils/AtlasResult.swift

#387: Handle network error

---

AtlasDemo/AtlasDemo/AppDelegate.swift
AtlasDemo/AtlasDemo/Main.storyboard
AtlasDemo/AtlasDemo/ProfileViewController.swift
AtlasUI/AtlasUI/CheckoutSummaryActionsHandler.swift
AtlasUI/AtlasUI/de.lproj/Localizable.strings

#390: Added fake/real switch for bug bashing

#390: Added fake/real switch

---

AtlasUI/AtlasUI/Utils/FormValidator.swift
AtlasUI/AtlasUITests/FormValidatorSpec.swift

Fixing number regex (found in Bug bashing) #428 
@bonkey there were tests but there were no numbers in the failure case :D

#428: NumberOnly regex

---

AtlasDemo/AtlasDemo/AppSetup.swift
AtlasDemo/AtlasDemo/Main.storyboard
AtlasDemo/AtlasDemo/ProfileViewController.swift

#243: Cherry picked live switch from BugBashing

#243: Cherry picked live switch from BugBashing

---

AtlasUI/AtlasUI/SizeSelectionViewController.swift

#342: Fixed "Pick a size" title.. Again.

#342: Fixed "Pick a size" title

---

AtlasDemo/AtlasDemo/AppSetup.swift
AtlasDemo/AtlasDemoUITests/AtlasDemoUITests.swift
AtlasUI/AtlasUI/AddressListTableViewDelegate.swift
AtlasUI/AtlasUI/AddressPickerViewController.swift
AtlasUI/AtlasUI/SizeListSelectionViewController.swift

#401: Fixed size selection bug

#401 + #445: Fixed size selection bug + Deleting non-selected address

---

AtlasUI/AtlasUI/SizeSelectionViewController.swift

#442: Added Cancel Button to pick a size screen

#442: Added Cancel Button to pick a size screen

---

AtlasUI/AtlasUI/CheckoutViewModel.swift
AtlasUI/AtlasUI/OAuth2LoginViewController.swift
AtlasUI/AtlasUI/de.lproj/Localizable.strings
AtlasUI/AtlasUI/en.lproj/Localizable.strings

#issue: 457 - Missing Translations

---

Gemfile
Gemfile.lock
calypso.rb
lib/calypso/issues.rb

#471: Added small helper to report github issues in list

#471: Added small helper to report github issues in list

---

.rubocop.yml
lib/calypso/ci.rb
lib/calypso/github.rb
lib/calypso/issues.rb

...if you write a script for doing it

#476: Writing release notes could be fun

---

AtlasUI/AtlasUI/BannerErrorViewController.swift
AtlasUI/AtlasUI/Utils/UserMessage.swift

#475: - displaying the error on the modals views as create address

---

AtlasSDK/AtlasSDK/Errors.swift
AtlasUI/AtlasUI/CheckoutSummaryViewController.swift
AtlasUI/AtlasUI/de.lproj/Localizable.strings
AtlasUI/AtlasUI/en.lproj/Localizable.strings

#431: show message when submit button is disabled

---

Gemfile
Gemfile.lock
lib/calypso/github.rb
lib/calypso/issues.rb

#484: Added querying whole project for cards

#484: Added querying whole project for cards

---

AtlasUI/AtlasUI/AddressActionsHandler.swift
AtlasUI/AtlasUI/AddressFormViewController.swift
AtlasUI/AtlasUI/AddressPickerViewController.swift
AtlasUI/AtlasUI/AtlasUIViewController.swift
AtlasUI/AtlasUI/CheckoutSummaryActionsHandler.swift
AtlasUI/AtlasUI/CheckoutSummaryViewController.swift
AtlasUI/AtlasUI/LoaderView.swift
AtlasUI/AtlasUI/SizeListSelectionViewController.swift
AtlasUI/AtlasUI/Utils/UIApplication.swift

#486: Unify the loader

---

AtlasDemo/AtlasDemo.xcodeproj/xcshareddata/xcschemes/AtlasDemo.xcscheme
AtlasUI/AtlasUI/BannerErrorViewController.swift
AtlasUI/AtlasUI/Utils/KeyboardScrollView.swift
AtlasUI/AtlasUI/Utils/TextFieldInputStackView.swift
AtlasUI/AtlasUI/Utils/UIView.swift

#511: Enhancing animation

---

AtlasDemo/AtlasDemo.xcodeproj/xcshareddata/xcschemes/AtlasDemo - Real API.xcscheme
AtlasUI/AtlasUI/de.lproj/Localizable.strings

fixing #530 
+
printing logs in real API

#530: Import from Address book translation

---

AtlasMockAPI/AtlasMockAPI/JSON/POST*|carts.json
AtlasSDK/AtlasSDK/Models/Cart.swift
AtlasUI/AtlasUI/AddressFormStackView.swift
AtlasUI/AtlasUI/AddressFormViewController.swift
AtlasUI/AtlasUI/CheckoutSummaryMainStackView.swift
AtlasUI/AtlasUI/CheckoutSummaryRootStackView.swift
AtlasUI/AtlasUI/Utils/UIBuilder.swift
AtlasUI/AtlasUITests/CheckoutSummaryViewControllerTests.swift

#544: removing sales channel from the response

---

AtlasDemo/AtlasDemo.xcodeproj/project.pbxproj
Gemfile.lock
README.md

#556: Added SDK requirements in README.md

#556: Added SDK requirements in README.md

---

Gemfile.lock
lib/calypso/consts.rb
lib/calypso/github_client/github_client.rb
lib/calypso/github_client/projects_api.rb
lib/calypso/issues.rb
lib/calypso/log.rb

#555: Added clean_closed task in calypso

#555: Added clean_closed task in calypso

---

AtlasDemo/AtlasDemo/AppSetup.swift
AtlasDemo/AtlasDemo/ProfileViewController.swift
AtlasSDK/AtlasSDK/Atlas.swift
AtlasSDK/AtlasSDKTests/AtlasTests.swift
AtlasUI/AtlasUI/SizeListSelectionViewController.swift
AtlasUI/AtlasUI/Utils/AtlasUI-AtlasAPIResult.swift
AtlasUI/AtlasUITests/LoggedInActionHandlerTests.swift

Rename login methods

---

AtlasUI/AtlasUI.xcodeproj/project.pbxproj
AtlasUI/AtlasUI/AddressFormDataModel.swift
AtlasUI/AtlasUI/AddressFormViewController.swift
AtlasUI/AtlasUITests/AddressFormViewControllerTests.swift
AtlasUI/AtlasUITests/LoggedInAddressListActionHandlerTests.swift

#566: Adding tests for addresses

---

AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|AD541L009-G11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|AZ711M001-B11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|GU121D08Z-Q11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|L2711E002-Q11.json
AtlasSDK/AtlasSDKTests/APIArticleTests.swift
AtlasUI/AtlasUI/CheckoutSummaryDataModel.swift
AtlasUI/AtlasUI/CheckoutSummaryLayout.swift
AtlasUI/AtlasUI/CheckoutSummaryMainStackView.swift
AtlasUI/AtlasUI/CheckoutSummaryViewModel.swift
AtlasUI/AtlasUI/SizeListSelectionViewController.swift
AtlasUI/AtlasUITests/LoggedInSummaryActionHandlerTests.swift

#573: Display prices even before login

---

AtlasDemo/buddybuild_postbuild.sh

Changed “verify” to “validate” in post build script

Changed “verify” to “validate” in post build script

---

AtlasSDK/AtlasSDK/Utils/Networking/URLComponents.swift
AtlasUI/AtlasUI/Utils/AtlasUI-URLRequest.swift
AtlasUI/AtlasUITests/URLRequestTests.swift

#528: Winning battle against login with "lng" query string

#528: Winning battle against login with "lng" query string

---

AtlasUI/AtlasUI.xcodeproj/project.pbxproj
AtlasUI/AtlasUI/ToCViewController.swift
AtlasUI/AtlasUI/Utils/AtlasUI-URL.swift
AtlasUI/AtlasUITests/URLRequestTests.swift
AtlasUI/AtlasUITests/URLTests.swift

#599: Added removing cookies from request to legal page

#599: Added removing cookies from request to legal page

---

AtlasSDK/AtlasSDK/Errors.swift
AtlasUI/AtlasUI/AddressBookImportDataModelCreationStrategy.swift
AtlasUI/AtlasUI/AddressFormDataModel.swift
AtlasUI/AtlasUI/de.lproj/Localizable.strings
AtlasUI/AtlasUI/en.lproj/Localizable.strings
AtlasUI/AtlasUI/fr.lproj/Localizable.strings
AtlasUI/AtlasUI/it.lproj/Localizable.strings
AtlasUI/AtlasUI/pl.lproj/Localizable.strings

#580: Check on the address country code

---

AtlasDemo/AtlasDemo/Assets.xcassets/AppIcon.appiconset/Contents.json
AtlasDemo/AtlasDemo/ProfileViewController.swift
AtlasMockAPI/AtlasMockAPI/Endpoints/guestOrder.swift
AtlasSDK/AtlasSDK.xcodeproj/project.pbxproj
AtlasSDK/AtlasSDK/AtlasAPIClient_public.swift
AtlasSDK/AtlasSDK/Endpoints/CompleteGuestOrderEndpoint.swift
AtlasSDK/AtlasSDK/Models/FormattableAddress.swift
AtlasSDK/AtlasSDK/Models/GuestCheckout.swift
AtlasSDK/AtlasSDK/Models/GuestOrderRequest.swift
AtlasSDK/AtlasSDKTests/APIGuestOrderTests.swift
AtlasUI/AtlasUI/GuestCheckoutSummaryActionHandler.swift

#604: Guest checkout with credit card

---

.codecov.yml

Removed ‘%’ from .codecov.yml

---

AtlasMockAPI/AtlasMockAPI/JSON/GET*|config.json
AtlasSDK/AtlasSDK/Models/Config.swift
AtlasSDK/AtlasSDKTests/ConfigTests.swift
AtlasUI/AtlasUI/NotLoggedInSummaryActionHandler.swift

#603: Guest Checkout enabled flag

---

AtlasDemo/buddybuild_postbuild.sh
AtlasSDK/AtlasSDKTests/ConfigTests.swift
AtlasSDK/AtlasSDKTests/TestConfig.swift

Cleanup tests around config

---

AtlasUI/AtlasUI/PaymentSelectionViewController.swift

#616: isWebKitError

---

AtlasSDK/AtlasSDK/Utils/Networking/URLRequest.swift
AtlasUI/AtlasUI/AddAddressTableViewCell.swift
AtlasUI/AtlasUI/PaymentSelectionViewController.swift

fixing #503 
starting from the wrong branch 😞  so we have also the updates about `isWebKitError `

#503: iPhone 6S Plus warning

---

AtlasSDK/AtlasSDK/Models/FormattableAddress.swift
AtlasUI/AtlasUI/GuestCheckoutSummaryActionHandler.swift
AtlasUI/AtlasUI/LoggedInSummaryActionHandler.swift

#672: Call cart & checkout Endpoint when changing the addresses

---

AtlasDemo/buddybuild_postbuild.sh
AtlasSDK/AtlasSDK/Errors.swift
AtlasUI/AtlasUI/GuestCheckoutSummaryActionHandler.swift
AtlasUI/AtlasUI/LoggedInSummaryActionHandler.swift
AtlasUI/AtlasUI/en.lproj/Localizable.strings
buddybuild_postclone.sh

#634: Missing payment method Error

---

AtlasSDK/AtlasSDK/Models/Money.swift
AtlasUI/AtlasUI/Utils/Localizer.swift
AtlasUI/AtlasUITests/LocalizationTests.swift

Tiny change, actually, but made as separated PR to play with codebeat

#703: Let’s ditch this old prick NSDecimalNumber

---

CONTRIBUTING.md

Nothing fancy. I could push it directly, but I was too lazy to switch settings ;-)

#711: Updated CONTRIBUTING.md

---

lib/calypso/env.rb

#720: [calypso] Dropped 2 unused methods

#720: [calypso] Dropped 2 unused methods

---

AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|AZ711M001-B11.json
AtlasMockAPI/AtlasMockAPI/JSON/POST*|carts.json
AtlasSDK/AtlasSDK/Models/Article.swift
AtlasUI/AtlasUI/AtlasUI.swift
AtlasUI/AtlasUI/CheckoutSummaryArticleSelectCollectionView.swift

#722: Supporting optional Stock for Article

---

AtlasUI/AtlasUI/de.lproj/Localizable.strings
AtlasUI/AtlasUI/en.lproj/Localizable.strings
AtlasUI/AtlasUI/fr.lproj/Localizable.strings
AtlasUI/AtlasUI/it.lproj/Localizable.strings
AtlasUI/AtlasUI/pl.lproj/Localizable.strings

Attention to details :-)
https://en.wikipedia.org/wiki/IDEAL

Update iDEAL capitalization in translations

---

AtlasSDK/AtlasSDK/Models/CheckoutAddresses.swift
AtlasSDK/AtlasSDK/Models/PickupPoint.swift
AtlasSDK/AtlasSDK/Models/StreetAddress.swift
AtlasUI/AtlasUI.xcodeproj/project.pbxproj
AtlasUI/AtlasUI/EmptyAddressDataModelCreationStrategy.swift
AtlasUI/AtlasUI/GuestAddressActionHandler.swift
AtlasUI/AtlasUI/LoggedInAddressListActionHandler.swift
AtlasUI/AtlasUI/LoggedInSummaryActionHandler.swift
AtlasUI/AtlasUI/ShippingAddressViewModelCreationStrategy.swift
AtlasUI/AtlasUI/Utils/FormattableAddress.swift
AtlasUI/AtlasUI/Utils/PickupPoint.swift
AtlasUI/AtlasUI/Utils/PickupPointType.swift
AtlasUI/AtlasUI/Utils/StreetAddress.swift
AtlasUI/AtlasUI/de.lproj/Localizable.strings
AtlasUI/AtlasUI/en.lproj/Localizable.strings
AtlasUI/AtlasUI/fr.lproj/Localizable.strings
AtlasUI/AtlasUI/it.lproj/Localizable.strings
AtlasUI/AtlasUI/pl.lproj/Localizable.strings
AtlasUI/AtlasUITests/LoggedInSummaryActionHandlerTests.swift

#593: Renaming Packstation

---

AtlasUI/AtlasUI/NotLoggedInSummaryActionHandler.swift

#728: Fixing quantity with GuestCheckout 

---

AtlasSDK/AtlasSDK/Models/SelectedArticle.swift
AtlasSDK/AtlasSDKTests/APICreateCheckoutTests.swift
AtlasUI/AtlasUI/CheckoutSummaryArticleSelectCollectionView.swift
AtlasUI/AtlasUI/CheckoutSummaryEditProductStackView.swift
AtlasUI/AtlasUI/CheckoutSummaryPriceStackView.swift
AtlasUI/AtlasUI/GetArticleDetailsViewController.swift
AtlasUI/AtlasUI/LoggedInSummaryActionHandler.swift
AtlasUI/AtlasUITests/CheckoutSummaryEditProductStackViewTests.swift
AtlasUI/AtlasUITests/GuestSummaryActionHandlerTests.swift
AtlasUI/AtlasUITests/LoggedInSummaryActionHandlerTests.swift
Gemfile
Gemfile.lock

#729: Check on new size quantity

---

AtlasUI/AtlasUI/ArticleNotSelectedActionHandler.swift
AtlasUI/AtlasUI/CheckoutContainerView.swift
AtlasUI/AtlasUI/CheckoutSummaryViewController.swift

#730: Fixing cancel the login screen for new design

---

AtlasDemo/AtlasDemo/DemoArticle.swift
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|AD541L009-G11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|AZ711M001-B11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|AZ711N007-Q11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|AZ711N00B-Q11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|EV451G023-Q11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|GU121D08Z-Q11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|L2711E002-Q11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|LA254E005-Q11.json
AtlasMockAPI/AtlasMockAPI/JSON/GET*|articles|MK151F00E-Q11.json
AtlasSDK/AtlasSDK/Models/Article.swift
AtlasSDK/AtlasSDKTests/APIArticleTests.swift

#752: Remaining changes for catalog API

---

AtlasDemo/AtlasDemo/ProductCollectionViewCell.swift
AtlasSDK/AtlasSDK.xcodeproj/project.pbxproj
AtlasSDK/AtlasSDK/AtlasAPIClient_public.swift
AtlasSDK/AtlasSDK/Endpoints/GetArticlesEndpoint.swift
AtlasSDK/AtlasSDK/Models/Article.swift
AtlasSDK/AtlasSDK/Models/Cart.swift
AtlasSDK/AtlasSDK/Models/CartItem.swift
AtlasSDK/AtlasSDK/Models/CartItemRequest.swift
AtlasSDK/AtlasSDK/Models/GuestCart.swift
AtlasSDK/AtlasSDK/Models/SKU.swift
AtlasSDK/AtlasSDK/Models/SelectedArticle.swift
AtlasSDK/AtlasSDK/Types.swift
AtlasSDK/AtlasSDKTests/APIArticleTests.swift
AtlasSDK/AtlasSDKTests/APICartTests.swift
AtlasSDK/AtlasSDKTests/APICreateCheckoutTests.swift
AtlasSDK/AtlasSDKTests/APIGuestCheckoutTests.swift
AtlasSDK/AtlasSDKTests/APIGuestOrderTests.swift
AtlasSDK/AtlasSDKTests/SKUTest.swift
AtlasUI/AtlasUI/AtlasUI.swift
AtlasUI/AtlasUI/AtlasUIViewController.swift
AtlasUI/AtlasUI/GetArticleDetailsViewController.swift
AtlasUI/AtlasUI/Utils/AtlasUIClient.swift
AtlasUI/AtlasUITests/CheckoutSummaryEditProductStackViewTests.swift
AtlasUI/AtlasUITests/UITestCase.swift

PR to #748 to make it more visible and more independent.
And, I'm not sure about it, too.

How aboout full-fledged SKU types?

---

lib/calypso/simctl.rb

#756: [calypso] Added simctl repopulate

#756: [calypso] Added simctl repopulate

---

AtlasSDK/AtlasSDK/API/AtlasAPI_endpoints.swift
AtlasSDK/AtlasSDK/API/Endpoints/GetArticleRecommendationsEndpoint.swift
AtlasUI/AtlasUI/CheckoutSummaryRecommendationStackView.swift
AtlasUI/AtlasUI/Utils/AtlasAPILoader.swift

#750: Supporting new recommendation headers

---

Sources/MockAPI/MockAPI/JSON/GET*|articles|AD541L009-G11.json
Sources/MockAPI/MockAPI/JSON/GET*|articles|AD541L009-G11|recommendations.json
Sources/MockAPI/MockAPI/JSON/GET*|articles|AZ711M001-B11.json
Sources/MockAPI/MockAPI/JSON/GET*|articles|AZ711M001-B11|recommendations.json
Sources/MockAPI/MockAPI/JSON/GET*|articles|AZ711N007-Q11.json
Sources/MockAPI/MockAPI/JSON/GET*|articles|AZ711N00B-Q11.json
Sources/MockAPI/MockAPI/JSON/GET*|articles|EV451G023-Q11.json
Sources/MockAPI/MockAPI/JSON/GET*|articles|GU121D08Z-Q11.json
Sources/MockAPI/MockAPI/JSON/GET*|articles|GU121D08Z-Q11|recommendations.json
Sources/MockAPI/MockAPI/JSON/GET*|articles|L2711E002-Q11.json
Sources/MockAPI/MockAPI/JSON/GET*|articles|L2711E002-Q11|recommendations.json
Sources/MockAPI/MockAPI/JSON/GET*|articles|LA254E005-Q11.json
Sources/MockAPI/MockAPI/JSON/GET*|articles|MK151F00E-Q11.json
Sources/MockAPI/MockAPI/JSON/GET*|articles|MK151F00E-Q11|recommendations.json
Sources/ZalandoCommerceAPI/ZalandoCommerceAPI/Models/Article.swift
Sources/ZalandoCommerceAPI/ZalandoCommerceAPI/Models/Media.swift
Sources/ZalandoCommerceAPI/ZalandoCommerceAPITests/APIArticleTests.swift
Sources/ZalandoCommerceDemoApp/ZalandoCommerceDemoApp/PDPViewController.swift
Sources/ZalandoCommerceUI/ZalandoCommerceUI/CheckoutSummaryRecommendationCollectionViewCell.swift

#775: handle the new type in media_items 

---

LICENSE
LICENSES

#787: Adding 3rd party licenses
